version: "3"

services:
  server:
    image: clarksam19/airlines:prod
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: airlines-prod
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./.env
    restart: always

networks:
  default:
    name: airlines-prod
