name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Client Dev Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: clarksam19/airlines-client:dev
          context: ./client

      - name: Build and Push Server Dev Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: clarksam19/airlines-server:dev
          context: ./server

      - name: Build and Push Prod Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: clarksam19/airlines:prod
